### ISSUE TITLE
[Question]: is it possible to build this project as `c-archive`?

### ISSUE THREAD

**Issue by TheAwesome98-Real** [PretendoNetwork/nex-go#72]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What would you like to know?

i'm writing a game server, and my favourite programming language is rust, so i'd like to write it in that. this is the most comprehensive nex implementation i've seen, and it would be extremely difficult for me, who is (technically) one person, to reimplement this in rust to be equal to this. so, i decided, it would be significantly easier to write rust bindings to this go package. i'd simply have to remember to free all pointers, and it shouldn't be too difficult to do. the problem arises when i actually try to build the package for rust. you see, i've only ever tried to write bindings for other c code, in which you simply call `cc` and tell it to build a `.a` file, then you tell `rustc` to use this `.a` file when linking. when looking around, i found you could tell the go compiler to output a `.a` file by using the command-line argument `-buildmode=c-archive`. the problem is, when i do this, `go` tells me `-buildmode=c-archive requires exactly one main package`. i don't really understand go, but from my experience with other languages, i would assume there is no main package, since this is a library. why does it require this? surely the option is there to build libraries? how do i fix it?

**Comment by binaryoverload** [comment]
Trying looking at this article: https://darkcoding.net/software/building-shared-libraries-in-go-part-1/

It seems to be that build mode needs to be `c-shared` which builds a standard library that can be linked to

I found this from https://users.rust-lang.org/t/can-rust-interface-with-go-libraries/4292/2

**Comment by TheAwesome98-Real** [comment]
fair enough. i'll probably just write my own version in rust, since having multiple implementations of standards is healthy

**Comment by jonbarrow** [comment]
I disagree that that is healthy, to be honest, but if you want to spend the time to rewrite everything then I wish you luck. I personally think the healthier thing to do would be to contribute back to a single implementation in a unified effort to create a solid implementation, rather than having many fragmented implementations of varying degrees of stability/features/API (at least until that implementation is considered truly stable, at which point ports would be much easier to make)

People have tried to make ports of libs before, in multiple languages, and they tend to end up being half-implemented and not really going anywhere, since it *is* a decently large undertaking. Do keep in mind that this is not the only library needed, this only implements the lower level PRUDP connections. You also need a way to handle the [protocols](https://github.com/PretendoNetwork/nex-protocols-go) and the [implementations of those protocols](https://github.com/PretendoNetwork/nex-protocols-common-go)

I tend to lean towards the opinion that fragmentation like that for no real reason outside of language preference only really ends up serving to divide rather than create a better ecosystem. Having many ports in many languages, which all have varying/different levels of support/features/stability, sounds much worse imo than just using and contributing towards one implementation with the goal of making it as stable as possible through unified effort. Working together to better a single implementation *has* worked out for the better in the past, this implementation would not be where it is today without the efforts of others who would have liked to use different languages (including Rust). And the efforts of people like [GoCentral](https://github.com/ihatecompvir/GoCentral) help pushed forward things like Rendez-Vous support for non-NEX clients

We're no strangers to language preferences for sure (99% of our stack is written in 2 languages, which we do mostly for consistency reasons, which is a real issue being solved by that decision), but we also recognize that trying to reinvent the wheel in a different language tends to be not great unless it's fixing an actual problem we have. For example [Pictobox](https://github.com/PretendoNetwork/pictobox) is a TypeScript implementation of many image formats, but this was made to fix the issue of existing JavaScript libraries not having APIs that tie in together very well (and the stack we needed to use these in was already TS/JS based), and some images had no libraries at all. So we implemented them ourselves to fill that need. On the other hand, [PKHaX](https://github.com/PretendoNetwork/PKHaX) (our Pokemon legality check server) is written in C#, and is the only server we have which is. This is because we rely on [PKHeX](https://github.com/kwsch/PKHeX) internally to do the legality checks, which is written in C#. We could have rewritten PKHeX into TS/JS in order to line up with the rest of our stack, but it wouldn't really solve an objective issue outside of language preference. Doing so would have just led to further tech debt on our end, now needing to maintain our own implementation which would almost certainly become out of date (which can and does happen, PKHeX constantly updates its rules for determining the legality of Pokemon like seen [here](https://forum.pretendo.network/t/can-an-illegal-pokemon-be-considered-a-cheat/8000)), requiring much more maintenance for basically no gain or else our implementation would become stale and further divided from the upstream version, while also contributing nothing back to the original authors

This is not meant to discourage you, to be clear (nor is it really meant to lecture, I just tend to write very long messages. It's a me thing), just giving my opinion/view on the matter as someone who has been working professionally in open source for many years now (I've been working on Pretendo since 2017, and have been an open source and freelance developer for several years prior to that) and seeing how often work ends up getting divided into 100 half-working implementations rather than people coming together to make one as good as it can be. I very often see repos with descriptions such as "*project* but in Rust!" or "*library* but in Python!" made by people who just like those languages, made without solving a problem outside of preference, and seeing they got some work done 5 years ago and then were never updated again past the basics

**Comment by ashquarky** [comment]
if you do actually do this (especially if it’s no_std) let me know because it would be portable to the consoles in a way that Go isn’t (for the reasons Jon described) and would be useful for homebrewI understand Jon’s point about fragmentation but there might be actual demand here which would keep the project aliveOn 27 Nov 2024, at 06:03, lily celeste newton ***@***.***> wrote:﻿
fair enough. i'll probably just write my own version in rust, since having multiple implementations of standards is healthy

**Comment by jonbarrow** [comment]
> if you do actually do this (especially if it’s no_std) let me know because it would be portable to the consoles in a way that Go isn’t (for the reasons Jon described) and would be useful for homebrewI understand Jon’s point about fragmentation but there might be actual demand here which would keep the project aliveOn 27 Nov 2024, at 06:03, lily celeste newton ***@***.***> wrote:﻿
> 
> fair enough. i'll probably just write my own version in rust, since having multiple implementations of standards is healthy
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

It would only be useful in the way you described if it had client support, which would need to be done from scratch seeing as this library can't act as a client right now. And if that's what you want, Cemu already has a PRUDPv0 implementation in C++ which is much more simplified than what we have here. A Rust port of this library is largely unnecessary even for what you've described

**Comment by TheAwesome98-Real** [comment]
the problem is i'm trying to implement this into a project that i've already written that uses rust crates and c libraries. that's why i don't think it makes sense to say i should contribute back to this project, even if i want to, because there's no reasonable way i can use it in my project. but anyway, i would only need to implement the minimum set of nex stuff to support that specific game server anyway, and if i open-source the crate it might possibly benefit someone else. that's why i don't think it's useful to say things like this:
> starting from scratch in Rust just for the sake of using Rust (which is a trend I've noticed online as of late...?)

you don't know why a user would want to use c/c++ or rust, just as i don't know why you want to use go for your project. i could easily say something stupid like "you use go because google made it", but that's probably not true, you probably use it because you've made go projects before, and you like that it's got garbage collection, or someone recommended it to you, or something.

**Comment by TheAwesome98-Real** [comment]
> I'm not aware of anything that needs only this library to function

it wouldn't be just this library, there are other things i need to implement, but they're all based on this, so it's the first thing i'd have to do

(actually reading this back yeah i can see how easily what i said was misintepreted, i meant to say i'd only have to implement the minimum that that game server supports)

my project itself is just an idea i want to see the viability of - it is multiple game servers within one. i've already written some of the psn component, because that's the only other game console online service that i'm familiar with, and i thought that the next thing i'd try to implement would be the wii u since it has good emulation, development tools, and the pretendo project is open-source.

**Comment by jonbarrow** [comment]
> my project itself is just an idea i want to see the viability of - it is multiple game servers within one

I can go ahead and give some insight on that now in case it prevents you from wasting time, since it's an idea that was thrown around on our end a while ago too

It's not very viable. Every game has a unique access key which is used as part of the packet validation and transport mechanisms. If you don't use the right key that the client expects, then the connection fails. And there's no way to heuristically know which client is being used outside of dedicated ports, which at that point it's no longer "in one". It might be the same process, sure, but it's not the same endpoint. Not to mention that different games use this access key in different ways, and some have completely unique ways of using it (Luigi's Mansion on the 3DS is one such game which uses its own algorithms)

On top of that, each game tends to vary in its configuration. Sometimes slightly, sometimes by a lot. Theres the difference in NEX/PRUDP versions obviously (which changes things like packet structure, acknowledgment mechanisms, RMC payload structures, etc.) but also even things like the packet MTU tend to vary, the largest variance being that of the friends server which has a very low MTU compared to other servers, though multiple other games also have different MTUs (the game clients seem kinda lenient on the MTU specifically but it's something to keep in mind). If you don't use the right library configuration for a game then the connection will be unstable at best, unusable at worst. Nintendo and 3rd parties didn't have to worry about this because the server library versions always matched the client, but for us we need to support all variants and thus each game has its own configuration

It's technically possible to get, like, super basic stuff working. You could probably get multiple games to establish a basic PRUDP connection if you patched the clients access keys to all be the same. But for actual game functionality you'd be hard pressed to get multiple actual games running on the same endpoint (PRUDP uses the concept of "endpoints" rather than "servers") unless unless their configs match 1:1 (which, again, normally isn't even possible due the differing access keys). At best you'd likely just have multiple endpoints with different configs running in the same process, but that's functionally no different than just having them in separate processes

And that's just issues with the basics. As I said PRUDP uses "endpoints" rather than servers, and advanced clients can establish multiple connections to the same address which all have their own isolated state through the virtual port system. These virtual connections can have completely different configurations as well, including their OWN access keys separate from the main one, so now you'd be managing THOSE on top of whatever you're trying to use to maintain the state of the differing client connections on the single endpoint

And that ignores the other logistical issues like general state management which sounds like it would be a nightmare

**Comment by TheAwesome98-Real** [comment]
the games i'm talking about are the same/very similar game, but on different systems. i only need nex for the wii u version, since it uses that

**Comment by jonbarrow** [comment]
Ah I see I apologize, I misunderstood. I thought the goal was to run many different NEX games via one server (such as running SMM, Splatoon, and MK8 all together at once). I see what you mean now. Sounds interesting! Good luck with that :+1:
